# SOPS configuration
# Secrets are encrypted with age key

creation_rules:
  - path_regex: \.enc\.yaml$
    age: age1lzu42skj9jmuk5a59muzz0qvgt9fyqfqu8395zu3j5fs3c2y6u3qhqxaem
  - path_regex: \.enc\.json$
    age: age1lzu42skj9jmuk5a59muzz0qvgt9fyqfqu8395zu3j5fs3c2y6u3qhqxaem
  - path_regex: \.enc$
    age: age1lzu42skj9jmuk5a59muzz0qvgt9fyqfqu8395zu3j5fs3c2y6u3qhqxaem
